### ISSUE TITLE
SQL error when searching for "informatik"

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#17]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORpackage IN (SELECT package FROM oer_block_edupublisher_metadata WHERE content ' at line 6
SELECT package, COUNT(package) AS cnt

                    FROM oer_block_edupublisher_metadata

                    WHERE 1=0
 OR (package IN (SELECT package FROM oer_block_edupublisher_metadata WHERE content LIKE ? AND active=1) ORpackage IN (SELECT package FROM oer_block_edupublisher_metadata WHERE content LIKE ? AND active=1)OR package IN (SELECT package FROM oer_block_edupublisher_metadata WHERE content LIKE ? AND active=1)) GROUP BY package ORDER BY cnt DESC LIMIT 20
[array (
  0 => '%informatik%',
  1 => '%%',
  2 => '%informatik %',
)]
Error code: dmlreadexception
* line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 522 of /blocks/edupublisher/externallib.php: call to mysqli_native_moodle_database->get_records_sql()
* line 228 of /lib/externallib.php: call to block_edupublisher_external::search()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by rschrenk** [comment]
Fixed in 5e125c436b2843aa4d95d85fdb3bfcaf0e7bfad9 and pulled as Hotfix to production system.
