### ISSUE TITLE
Recover preview-button

### ISSUE THREAD

**Issue by rschrenk** [center-for-learning-management/moodle-block_edupublisher#18]
When searching in edupublisher results show a preview-button. This button has disappeared and needs to be recovered.

**Comment by rschrenk** [comment]
Solved in 17d78614a45c656954faa7d804f0e680c17160a2
@lassnj Please review on staging system.

**Comment by lassnj** [comment]
Preview button is back, but I think it originally was blue?

**Comment by rschrenk** [comment]
According to screenshots from a slideshow we used in August, it was gray.

**Comment by rschrenk** [comment]
Merge into 20_35_2_minor 284539b

**Comment by rschrenk** [comment]
Now in production.
