### ISSUE TITLE
eduvidual access-cards: wrong order in export file

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#21]
Note: couldn't find the correct repository to add the issue.

Problem: When exporting the access cards as csv, excel, etc. the last two columns are reversed:

![image](https://user-images.githubusercontent.com/22933650/73173816-84b0a600-4106-11ea-96e7-8977338a7966.png)

**Comment by rschrenk** [comment]
Fixed 10b8d116acc0f0d79384cbdaa73e5f4b256d1ed3

**Comment by rschrenk** [comment]
Merge into branch for 20_35_2_minor

**Comment by rschrenk** [comment]
Now in production.
