### ISSUE TITLE
Redirect Error Microsoft Login

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#24]
When first name and last name are empty in the Microsoft account, a redirection error occurs in eduvidual and the users cannot access the application. Add exception handling.

**Comment by rschrenk** [comment]
This is the wrong plugin. This issue should go to moodle-block_eduvidual.

**Comment by rschrenk** [comment]
solved in block-eduvidual in commit 13ae98404c3c37beca3d55a287bed12016867340

**Comment by rschrenk** [comment]
PS: Needs review once the current master is published on our production site.
