### ISSUE TITLE
teachers cannot access ressource search

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#39]
teachers cannot access the link (error: guests are not allowed)
[https://t1.eduvidual.org/blocks/edupublisher/pages/search.php](https://t1.eduvidual.org/blocks/edupublisher/pages/search.php)

Tested with lisa

**Comment by rschrenk** [comment]
this is not a bug, but a configuration issue on the test system. Granted the role "Authenticated Users" the capability to use search and it works now.
