### ISSUE TITLE
etapa Evaluation fails with A required parameter (packageid) was missing

### ISSUE THREAD

**Issue by bkasel** [center-for-learning-management/moodle-block_edupublisher#46]
I am trying out the edupublisher module and I am trying to publish an activity as etapa. 
When I (admin) try to evaluate the etapa, the process fails when I click save changes.

![grafik](https://user-images.githubusercontent.com/16179803/104232162-3b10b680-5450-11eb-8447-fb11a213f070.png)

![grafik](https://user-images.githubusercontent.com/16179803/104232037-07ce2780-5450-11eb-8576-3a6893c06b17.png)

I am using the most recent commit [d57dc08](https://github.com/center-for-learning-management/moodle-block_edupublisher/commit/d57dc0881739e3e04d0c2b41559fa766283df024) on an ubuntu 20.04lts system with moodle 3.10 (had the same problem with 3.9)

**Comment by rschrenk** [comment]
Hello,
the feature to make evaluations is not yet working. It is a planned as feature for future versions.
Kind regards
