### ISSUE TITLE
eTapas without guest access and key required

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#47]
There are some published eTapas that don't have guest access configured: 
[https://www.eduvidual.at/course/view.php?id=66619#](https://www.eduvidual.at/course/view.php?id=66619#)
[https://www.eduvidual.at/course/view.php?id=66625](https://www.eduvidual.at/course/view.php?id=66625)

Most eTapas now require a subscription key in order to view / use them

**Comment by rschrenk** [comment]
fixed.

```
require_once($CFG->dirroot . '/blocks/edupublisher/block_edupublisher.php');
$packages = $DB->get_records('block_edupublisher_packages', array('active' => 1));
foreach ($packages as $package) { 
    echo "Fixing #$package->id course $package->course $package->title<br />\n";
    block_edupublisher::toggle_guest_access($package->course, 0);
    block_edupublisher::toggle_guest_access($package->course, 1);
}
```
