### ISSUE TITLE
Die Abhängigkeitsprüfung fehlgeschlagen 

### ISSUE THREAD

**Issue by Oke-Anyanwu** [center-for-learning-management/moodle-block_edupublisher#49]
Bei Installation schlug die Plugin-Abhängigkeitsprüfung fehl. Als  "Fehlend" und "Nicht verfügbar" hat das System "local_komettranslator (2021031200)" gemeldet. Wo bekommt man local_komettranslator (2021031200), um die Plugin-Anforderungen gelöst zu bekommen?

**Comment by rschrenk** [comment]
Hallo, der master-branch ist unser Entwicklungszweig. Dieses zusätzliche Plugin ist in Entwicklung und daher noch nicht öffentlich verfügbar. Bitte benutzen Sie die Version im Branch https://github.com/center-for-learning-management/moodle-block_edupublisher/tree/20_39_12_major
