### ISSUE TITLE
fetch_curl is not CFG->proxyauth/proxyuserpwd/httpproxytunnel/proxytype/proxy aware

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-block_edupublisher#54]
Hallo @rschrenk 

Die Funktion ```fetch_curl``` re-implementiert [lib/filelib.php curl()](https://github.com/moodle/moodle/blob/17ee0726933c7c6410aca0e1edc445f795774c07/lib/filelib.php#L3114) nicht vollständig:

https://github.com/center-for-learning-management/moodle-block_edupublisher/blob/8d9c3685184d75f0691647811f2eaaaf40fd8b6c/classes/externalsources.php#L451-L474

Es fehlen u.A. die ganzen PROXY Settings

links-to: https://github.com/center-for-learning-management/eduvidual-infrastructure/issues/1037

**Comment by gtndevel** [comment]
Implemented.
