### ISSUE TITLE
hardcoded URL

### ISSUE THREAD

**Issue by GGeorggg** [center-for-learning-management/moodle-block_edupublisher#55]
Hallo @gtndevel 

da gibt es einen hardcodierten URL:

https://github.com/center-for-learning-management/moodle-block_edupublisher/blob/333f6f51b7b679e7806ce4d92e643218ed2ecc07/templates/block.mustache#L36

könnt ihr euch das bitte anschauen - danke

**Comment by gtndevel** [comment]
habs gefixed!
