### ISSUE TITLE
Gast User sieht Menüpunkt Ressourcenkatalog nicht

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#64]
Gast User sehen den Menüpunkt Ressourcenkatalog nicht, alle anderen Logged in oder not logged in Users sehen den Menüpunkt. 
Bei dieser Gelegenheit, bitte auch den Menüpunkt von 

https://github.com/center-for-learning-management/moodle-local_eduvidual/blob/497de009b7780bc394e5197d27ce0bb73c155d27/lib.php#L306-L307

in den Block edupublisher holen

### Schritte zum Reproduzieren
- öffne [eduvidual.at](https://www.eduvidual.at/) in einem privaten Fenster
- der Menüpunkt Ressourcenkatalog wird angezeigt und im Footer steht "Sie sind nicht angemeldet. ([Login](https://www.eduvidual.at/login/index.php))"
- klicke auf den Menüpunkt Ressourcenkatalog
- Der Menüpunkt Ressourcenkatalog verschwindet und im Footer steht "Sie sind als Gast angemeldet ([Login](https://www.eduvidual.at/login/index.php))"
- Klicke erneut auf eduvidual.at, um auf die Startseite zu gelangen
- Anmeldung als Gast bleibt bestehen und der Menüpunkt Ressourcenkatalog bleibt verschwunden

am t4 wird der Menüpunkt auch nicht angemeldeten Nutzer/innen nicht angezeigt. Da im Ressourcenkatalog OER Materialien publiziert sind, sollte dieser Menüpunkt jederzeit unabhängig von der Anmeldung und Rolle im System angezeigt werden

**Comment by lassnj** [comment]
@ariepl FYI

**Comment by prowebat** [comment]
@lassnj 
1) ich würde alle speziellen Menüpunkte am besten an einer Stelle lassen (local_eduvidual) und nicht in den einzelnen Modulen.
Grüde u.A.: einfacher zu warten, die Reihenfolge kann individuell bestimmt werden.
2) technisch kann den Menüpunkt schon in local_edupublisher geben, dann würde er aber am Ende angehängt.

**Comment by lassnj** [comment]
> * ich würde alle speziellen Menüpunkte am besten an einer Stelle lassen (local_eduvidual) und nicht in den einzelnen Modulen.
>   Grüde u.A.: einfacher zu warten, die Reihenfolge kann individuell bestimmt werden.

@prowebat ich bin durch die Abhängigkeit vom block_edupublisher in local_eduvidual beim behat-test gescheitert. Daher die bevorzugte Trennung, außerdem soll das Plugin edupublisher auch unabhängig von local_eduvidual funktionieren. Design-Prinzip Encapsualtion sollte berücksichtigt werden.

> * technisch kann den Menüpunkt schon in local_edupublisher geben, dann würde er aber am Ende angehängt.

das ist kein Problem, dann ist der Menüpunkt wenigstens immer an der gleichen Stelle. Die Reihenfolge ist nicht so wichtig, Hauptsache er ist da ;)

**Comment by prowebat** [comment]
so, das hat sich wohl erübrigt, da die Navigation nur von Local-Plugins und Modulen (bei denen nur im aktuellen Kurs) geändert werden kann.

**Comment by lassnj** [comment]
> so, das hat sich wohl erübrigt, da die Navigation nur von Local-Plugins und Modulen (bei denen nur im aktuellen Kurs) geändert werden kann.

alles klar, danke für die Info 😢 Dann muss ich wohl eine andere Lösung für meinen behat test finden.

Gastuser sollten den Menüpunkt aber trotzdem auch sehen, das Verschieben war nur ein Zusatzwunsch. Dass der Menüpunkt für Gastuser verschwindet ist ein Bug. Danke!

**Comment by sanjan1809** [comment]
Jetzt ist in der Menüleiste ohne Anmeldung folgendes zu sehen:

![Image](https://github.com/center-for-learning-management/moodle-block_edupublisher/assets/79969581/108f5023-45ab-40b6-94a7-96fb687075c5)

"Meine Schulen" und "Kurs erstellen" soll nur für angemeldete User sichtbar sein...

**Comment by lassnj** [comment]
Das sieht man jetzt auch. 
![grafik](https://github.com/center-for-learning-management/moodle-block_edupublisher/assets/22933650/93e6ac2d-b9cb-4b9a-a8ff-3fa3f66ac142)
@sanjan1809 bitte in ein eigenes Ticket für Semesterupdate

**Comment by sanjan1809** [comment]
Ticket für Semesterupdate: https://github.com/center-for-learning-management/eduvidual-src/issues/1618
