### ISSUE TITLE
eduthek.neu Feature Branch

### ISSUE THREAD

**Issue by rschrenk** [center-for-learning-management/moodle-block_edupublisher#67]
Hallo @prowebat 
wie besprochen, bitte diesen Branch mal in einer Testumgebung deployen:
https://github.com/center-for-learning-management/moodle-block_edupublisher/tree/feature_channel_eduthek-neu

**Comment by prowebat** [comment]
Lieber @rschrenk 
habe die eduthek branch am t4 eingebunden:
https://t4.eduvidual.org/

**Comment by rschrenk** [comment]
danke, ich habe wohl eine Spalte vergessen:
![grafik](https://github.com/center-for-learning-management/moodle-block_edupublisher/assets/8080807/feb6ea9c-f12d-4bdb-afdb-e4b8faf17ae2)

Habe ein Upgrade im Branch hochgeladen. Kannst du bitte das Update deployen?

**Comment by prowebat** [comment]
@rschrenk 
ist upgedated.

**Comment by rschrenk** [comment]
danke sehr! Habe die letzten erforderlichen Bugfixes in den Branch hochgeladen. Kannst du es bitte noch einmal deployen? Ich denke aber, dass man es so ins Produktivsystem dann übernehmen kann.

**Comment by prowebat** [comment]
@rschrenk 
hab den edupublisher am t4 upgedated.

**Comment by rschrenk** [comment]
habs getestet. Funktioniert nun so wie es soll. Kann in die eduvidual-Produktivumgebung deployed werden, damit das Redaktionsteam mit seiner Arbeit beginnen kann!

**Comment by prowebat** [comment]
@sanjan1809 @lassnj 
kann der aktuelle Stand in den Master gemerged werden, damit es im Sommerupdate mit kommt?

**Comment by lassnj** [comment]
@prowebat von meiner Seite spricht nix dagegen.

**Comment by lassnj** [comment]
@rschrenk ich bekomme beim Veröffentlichen meiner Ressource am Testsystem 
![grafik](https://github.com/center-for-learning-management/moodle-block_edupublisher/assets/22933650/77dfa353-04a8-4df5-bba5-c9f30d27febb)
https://test.eduvidual.at/course/view.php?id=175218

ich kann die Veröffentlichung auch nicht mehr fortsetzen.
![grafik](https://github.com/center-for-learning-management/moodle-block_edupublisher/assets/22933650/e0a4f76c-1d69-4840-8adc-529735d6a497)

**Comment by rschrenk** [comment]
Seltsam, an dem Teil habe ich eigentlich nichts geändert. Der Fehler betrifft auch den Eintrag im "default"-Channel:
https://github.com/center-for-learning-management/eduvidual-src/issues/1979#issuecomment-2223202184
Habe jedenfalls ein Update bereitgestellt. Damit wird zuerst geprüft, ob es den Eintrag in der Subtabelle schon gibt.

https://github.com/center-for-learning-management/moodle-block_edupublisher/tree/feature_channel_eduthek-neu

**Comment by rschrenk** [comment]
Ich habe soeben mit dem zuletzt bereitgestellten Update auf T4 getestet, ein neues Paket freizugeben. Das hat problemlos geklappt. Leider kann ich in der Testumgebung nicht ausrollen...

**Comment by rschrenk** [comment]
@GGeorggg 
ich denke, dass @lassnj auf Urlaub ist. Könntest du bitte im Testsystem nochmal den aktuellen Stand vom branch ausrollen?
LG

**Comment by GGeorggg** [comment]
Hallo @rschrenk 

[Änderungen](https://github.com/center-for-learning-management/moodle-block_edupublisher/compare/0ae2dcf639b178f610e6b51ffe35007270819165...31f63975b665d2d5b800d7c02f11a9e34f8e7cf6) wurden in ```eduvidual_404_stable``` und ```staging``` aufgenommen und in die Staging Umgebung deployed

lg
Georg

**Comment by rschrenk** [comment]
unter staging.eduvidual.at kann ich leider mit meinem Konto nicht rein.

Ich habe gerade mittels SSO mit Mama Curie angemeldet - ist es Absicht, dass Mama Curie Website-Admin ist??? Bin mir da nicht so sicher, ob das nicht Daniels Admin-Konto war und er es unabsichtlich gemapped hat:

![grafik](https://github.com/user-attachments/assets/173dc8c6-5d91-475b-a69b-4f106d0aec38)

**Comment by prowebat** [comment]
@rschrenk 
das war ein Test von mir, ob die Verknüpfung der Benutzer funktioniert.
Werd diese aufheben.

Brauchst du einen Admin Account für Staging?

**Comment by rschrenk** [comment]
Normalerweise nicht, aber nachdem Julia auf Urlaub ist wollte ich testen, ob das eduPublisher Update funktioniert. Am T4 hat es jedenfalls geklappt.

**Comment by prowebat** [comment]
Feature Branch wurde in den master gemerged, darum schließe ich das ticket
