### ISSUE TITLE
Falscher Blockinhalt bei Verwendung Inhalte Ressourcenkatalog

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#69]
Wenn Inhalte aus dem Ressourcenkatalog verwendet werden und in den eigenen Kurs kopiert werden, sollte im Block edupublisher angezeigt werden, dass Inhalte des eigenen Kurses auf einem Kurs im Ressourcenkatalog basieren, mit Link auf den entsprechenden Kurs:
![grafik](https://github.com/user-attachments/assets/6a777438-9372-4c35-ae04-1b2de201583c)

Es wird aber nur der Link zum Veröffentlichen eigener Inhalte angezeigt:
![grafik](https://github.com/user-attachments/assets/7370eb00-12f8-436b-bad8-b375aead27fa)

Beispielkurs: 
https://test.eduvidual.at/course/view.php?id=134754
Hier ist nur der Abschnitt allgemeines "eigene Inhalte". Der Rest ist der Inhalt des eTapas 
https://test.eduvidual.at/course/view.php?id=19344

**Comment by prowebat** [comment]
@lassnj 
Prio?
Hast du auch ein Beispiel dafür auf t4 oder Prod? (gut, dass der t4 noch alt ist ;) )

**Comment by lassnj** [comment]
@prowebat t4: https://t4.eduvidual.org/course/view.php?id=8
Habe das Lernpaket https://t4.eduvidual.org/course/view.php?id=189 in diesen Kurs kopiert.

Prio: machen wir für's Herbstupdate 2024.

**Comment by prowebat** [comment]
das Logging, welche Edupublisher Pakete im Kurs verwendet werden, wurde im Mai 2020 gelöscht.
Somit gibt es seitdem keine Daten.
Ich hab das wieder hinzugefügt.

Sieht dann so aus:
![image](https://github.com/user-attachments/assets/02c2a4ed-47c4-4d60-987d-eac454ffa64d)

**Comment by prowebat** [comment]
Ist auf test maxima01 deployed.
Test-Kurs:
https://test.eduvidual.at/course/view.php?id=67611

**Comment by lassnj** [comment]
![grafik](https://github.com/user-attachments/assets/897a1506-5c91-4b9e-af58-0e4a3e4828f4)

@prowebat Der "Veröffentlichung fortsetzen"  Link sollte mit dem neuen Block dann nicht mehr verfügbar sein. Eigentlich sollte ich den Block als Lehrer nicht mehr hinzufügen können, weil das ja dann alles über das Einreichformular automatisch befüllt wird, bzw. wenn ich Ressourcen aus der eduthek dupliziere, dann kommt der ja auch automatisch in meinen Kurs, damit ich weiß, woher ich mein Zeug bezogen habe oder? Ich würde dann die Rechte zum Hinzufügen des Blocks eduPublisher der Rolle Lernbegleiter/in entziehen.

**Comment by prowebat** [comment]
> Der "Veröffentlichung fortsetzen" Link sollte mit dem neuen Block dann nicht mehr verfügbar sein.

ja, den kann man weggeben.

> Eigentlich sollte ich den Block als Lehrer nicht mehr hinzufügen können, weil das ja dann alles über das Einreichformular automatisch befüllt wird, bzw. wenn ich Ressourcen aus der eduthek dupliziere, dann kommt der ja auch automatisch in meinen Kurs,

genau.

> Ich würde dann die Rechte zum Hinzufügen des Blocks eduPublisher der Rolle Lernbegleiter/in entziehen.

ich würds so lassen wie es jetzt ist. Stört ja keinen, wenn man ihn hinzufügen kann.
Außerdem, was ist wenn ich den versehentlich im experten-Modus lösche, dann ist er weg...

**Comment by lassnj** [comment]
> Außerdem, was ist wenn ich den versehentlich im experten-Modus lösche, dann ist er weg...

stimmt, dann lassen wir die Rechte. Bitte die Möglichkeit zum Veröffentlichen in dem Block ausbauen. Danke!

**Comment by prowebat** [comment]
passt.
