### ISSUE TITLE
Channel Export eduthek.neu

### ISSUE THREAD

**Issue by rschrenk** [center-for-learning-management/moodle-block_edupublisher#70]
Leider wurde vergessen beim Task `channel_export` die eduthek.neu zu berücksichtigen. Bitte um Hotfix!

LG

**Comment by rschrenk** [comment]
Commit bereitgestellt.

**Comment by rschrenk** [comment]
Leider hat es scheinbar keine Ausrollung gegeben. Wir können die eduthek.neu-Inhalte immer noch nicht abrufen:

![grafik](https://github.com/user-attachments/assets/c79b5562-70f6-4754-a21a-875d386b4026)

**Comment by prowebat** [comment]
Gibt es schon Inhalte im dem Channel?
