### ISSUE TITLE
Spalte Status und eTapa sortierbar machen

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-block_edupublisher#75]
Bitte die Spalten Status und eTapa sortierbar machen:

https://www.eduvidual.at/blocks/edupublisher/pages/list.php
![grafik](https://github.com/user-attachments/assets/c83317f6-dc6f-4d36-b220-9591ed7ef70b)

**Comment by prowebat** [comment]
ist geändert und wird am Montag Abend ausgerollt:
* Status-Spalte kann sortiert und gefiltert werden
* Eingereicht-Spalte ergänzt (das wird aber nur für neue Einreichungen befüllt)

![image](https://github.com/user-attachments/assets/e8c9fa86-c7d9-43e9-8c2b-b1714a1b7e20)

offen: eTapa spalte sortierbar
